config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
  f_dir_colors:
    src: dir_colors
    dst: ~/.dir_colors
  f_alacritty.yml:
    src: config/alacritty/alacritty.yml
    dst: ~/.config/alacritty/alacritty.yml
  f_tmux.conf:
    src: tmux.conf
    dst: ~/.tmux.conf
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
profiles:
  juan-hp:
    dotfiles:
    - f_vimrc
    - f_dir_colors
    - f_alacritty.yml
    - f_tmux.conf
    - f_bashrc
    - f_gitconfig
